import Navbar from './component/navbar/Navbar';
import { Context, MyContextProvider } from './context/Context';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const showInitialInfoCard = true;
  return (
    <html lang="en">
      <MyContextProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </MyContextProvider>
    </html>
  );
}
